In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:\\Users\\gajen\\Downloads\\Forest_fire.csv')

In [3]:
data.head(5)

        Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1

In [6]:
data.describe()

          Oxygen  Temperature    Humidity  Fire Occurrence
count  39.000000    39.000000   39.000000        39.000000
mean   33.846154    33.794872   36.282051         0.512821
std    23.734872    16.225677   28.046905         0.506370
min     0.000000     0.000000    0.000000         0.000000
25%    11.500000    20.000000   13.500000         0.000000
50%    30.000000    35.000000   30.000000         1.000000
75%    50.000000    45.000000   62.500000         1.000000
max    89.000000    60.000000  100.000000         1.000000

In [7]:
data.isnull().sum()

Area               10
Oxygen              0
Temperature         0
Humidity            0
Fire Occurrence     0
dtype: int64

In [8]:
data.columns

Index(['Area', 'Oxygen', 'Temperature', 'Humidity', 'Fire Occurrence'], dtype='object')

In [9]:
data.shape

(39, 5)

In [10]:
data.ndim

2

In [11]:
data.head(5)

        Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1

In [12]:
data.drop('Area',axis=1,inplace=True)

In [13]:
data.head(5)

   Oxygen  Temperature  Humidity  Fire Occurrence
0      40           45        20                1
1      50           30        10                1
2      10           20        70                0
3      60           45        70                1
4      30           48        10                1

In [19]:
x = data.drop('Fire Occurrence',axis=1)
y = data['Fire Occurrence']

In [20]:
print(x.shape)
print(y.shape)

(39, 3)
(39,)

In [21]:
x.head()

   Oxygen  Temperature  Humidity
0      40           45        20
1      50           30        10
2      10           20        70
3      60           45        70
4      30           48        10

In [22]:
y.head()

0    1
1    1
2    0
3    1
4    1
Name: Fire Occurrence, dtype: int64

#Traintest Split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape )

(31, 3)
(8, 3)
(31,)
(8,)

#Preprocessing

In [26]:
from sklearn.preprocessing import Normalizer

In [27]:
scaler = Normalizer().fit(x_train)
Normalizer_x = scaler.transform(x_train)
Normalizer_x_test = scaler.transform(x_test)

#Apply Algorithm

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
model = LogisticRegression()

In [30]:
model.fit(x_train,y_train)

LogisticRegression()

#Check Accuracy Training

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
x_train_pre = model.predict(x_train)

training_data_accuracy = accuracy_score(x_train_pre,y_train)

In [33]:
training_data_accuracy

1.0

#Check Accuracy Testing

In [34]:
x_test_pre = model.predict(x_test)

testing_data_accuracy = accuracy_score(x_test_pre,y_test)

In [35]:
testing_data_accuracy

1.0

#Save pickle file

In [36]:
import pickle

In [37]:
file = 'one.pkl'

In [38]:
pickle.dump(model,open(file,'wb'))

#loading the file

In [40]:
one = pickle.load(open('one.pkl','rb'))

In [41]:
one

LogisticRegression()

#Output

In [51]:
input_data = (40,27,50)

input_np = np.asarray(input_data)

reshape = input_np.reshape(1,-1)

prediction = one.predict(reshape)
print(prediction)

if (prediction[0] == 0):
  print('No Fire')
else:
  print('Fire')

[0]
No Fire

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(